pipeline {
  agent {
    docker { image 'node:16-alpine' } // Use Node.js Alpine image
  }
  stages {
    stage('Test') { // Define test stage
      steps {
        sh 'node --version' // Print Node.js version
      }
    }
  }
}

