pipeline {
  agent none // Define that no agent is specified at the pipeline level
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' } // Use Maven and AdoptOpenJDK Docker image as agent for this stage
      }
      steps {
        sh 'mvn --version' // Print Maven version
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' } // Use Node.js Alpine image as agent for this stage
      }
      steps {
        sh 'node --version' // Print Node.js version
      }
    }
  }
}
